language: d

jobs:
  include:
    - name: "Linux DMD"
      os: linux
      dist: jammy
      d: dmd-nightly
    - name: "Mac DMD"
      os: osx
      osx_image: xcode13.4
      d: dmd-nightly
    - name: "Linux LDC"
      os: linux
      dist: jammy
      d: ldc-latest-ci
    - name: "Mac LDC"
      os: osx
      osx_image: xcode13.1
      d: ldc-latest-ci
    - name: "Linux GDC"
      os: linux
      dist: jammy
      d: gdc

script:
  - bash ./.travis.sh
