language: d

jobs:
  include:
    - name: "Linux DMD"
      os: linux
      dist: focal
      d: dmd-nightly
    - name: "Mac DMD"
      os: osx
      osx_image: xcode13.1
      d: dmd-nightly
    - name: "Linux LDC"
      os: linux
      dist: focal
      d: ldc-latest-ci
    - name: "Mac LDC"
      os: osx
      osx_image: xcode13.1
      d: ldc-latest-ci
    # - name: "Linux GDC"
    #   os: linux
    #   dist: focal
    #   d: gdc

script:
  - bash ./.travis.sh
